baseURL = "https://admin-eworld.github.io/esg-reporting-comparisons/"
languageCode = "en-us"
title = "ESG Comparison Reports"
theme = "simple-esg-theme"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Trading Tools"
    url = "/trading-tools/"
    weight = 2
